0. 리스트를 비롯한 여러 가지 자료구조에 사용할 수 있는 내장 함수에는 `len()`, `sum()`, `min()`, `max()` 외에도  `all()`, `any()`, `sorted()`, `reversed()` 등이 있다. 이들 함수를 사용하는 예제 프로그램을 작성하시오.

In [15]:
print(all([1,2,3])) #반복 가능한 자료형x를 입력 인수로 받으며 x가 참이면 True, 거짓이 하나라도 있으면 False를 출력
print(any([1,2,3,0])) #x중 하나라도 참이 있을 경우 True를 출력, x가 모두 거짓일 경우에만 False를 출력
print(sorted([3,2,1])) #입력값을 정렬한 후 그 결과를 리스트로 리턴하는 함수
s="python" 
print(list(reversed(s)))

True
True
[1, 2, 3]
['n', 'o', 'h', 't', 'y', 'p']

1. 리스트 자료구조의 `reverse()` 메소드에 대해서 알아보시오.

In [19]:
# 리스트를 역순으로 뒤집어 준다. 현재의 리스트를 그대로 거꾸로 뒤집을 뿐이다.
abc = ["a","b","c"]
abc.reverse()
abc

['c', 'b', 'a']

2. 다음 코드의 실행 결과를 예상해보시오.
```python
a = [1, 2]
b = [3, 4, 5]
a.append(b)
b = b + a
```

In [0]:
a= [1,2]
b= [3,4,5]
a.append(b) # [1,2,[3,4,5]]
b=b+a # [3,4,5,[1,2]]

3. 다음은 여러 국가의 일인당 연간 포도주 소비량과 심장병으로 인한 사망율을  측정한 **심장병자료**이다.

    * **심장병자료**를 이름이 country, wine, death인 list 객체에 저장하시오.
    * 각 list 객체에 저장된 값의 개수를 확인하시오.
    * wine, death에 저장된 값의 합, 평균, 편차, 편차 제곱합, 표준편차를 계산하시오.

| country | wine | death_rate |
|:------ | ----:|----------:|
| Australia | 2.5 | 211 |
| Austria | 3.9 | 167 |
| Belgium/Luxembourg | 2.9 | 131 |
| Canada | 2.4 | 191 |
| Denmark | 2.9 | 220 |
| Finland | 0.8 | 297 |
| France | 9.1 | 71 |
| Iceland | 0.8 | 211 |
| Ireland | 0.7 | 300 |
| Italy | 7.9 |  107 |
| Netherlands | 1.8 | 167 |
| New Zealand | 1.9 | 266 |
| Norway | 0.8 | 227 |
| Spain | 6.5 | 86 |
| Sweden | 1.6 | 207 |
| Switzerland | 5.8 | 115 |
| United Kingdom | 1.3 | 285 |
| United States | 1.2 | 199 |
| West Germany | 2.7 | 172 |

In [0]:
country=["Australia","Austria"," Belgium/Luxembourg","Canada"," Denmark",\
         "Finland","France","Iceland","Ireland","Italy",\
         "Netherlands","New Zealand","Norway","Spain","Sweden",\
         "Switzerland","United Kingdom","United States","West Germany"]
wine=[2.5, 3.9, 2.9, 2.4, 2.9, 0.8, 9.1, 0.8, 0.7, 7.9, 1.8, 1.9, 0.8, 6.5, 1.6, 5.8, 1.3, 1.2, 2.7]
death_rate=[211, 167, 131, 191, 220, 297, 71, 211, 300, 107, 167, 266, 227, 86, 207, 115, 285, 199, 172]

In [33]:
country_n = len(country)
wine_n = len(wine)
death_rate_n = len(death_rate)
print(country_n, wine_n, death_rate_n)

19 19 19

In [41]:
wine_sum = sum(wine)
death_rate_sum = sum(death_rate)
print(wine_sum, death_rate_sum)

import numpy as np
wine_mean = np.mean(wine)
death_rate_mean = np.mean(death_rate)
print(wine_mean, death_rate_mean)

wine_dev=[]
death_rate_dev=[]
for wn in wine:
  wine_dev.append(wn - wine_mean)
for dr in death_rate:
  death_rate_dev.append(dr - death_rate_mean)
print(wine_dev)
print(death_rate_dev)

import math
wine_sse = 0
death_rate_sse = 0
for wn_dev in wine_dev:
  wine_sse = wine_sse + math.pow(wn_dev,2)
for dr_dev in death_rate_dev:
  death_rate_sse = death_rate_sse + math.pow(dr_dev, 2)
print(wine_sse, death_rate_sse)

wine_std = np.std(wine)
death_rate_std = np.std(death_rate)
print(wine_std, death_rate_std)

57.49999999999999 3630
3.026315789473684 191.05263157894737
[-0.5263157894736841, 0.8736842105263158, -0.12631578947368416, -0.6263157894736842, -0.12631578947368416, -2.2263157894736842, 6.073684210526316, -2.2263157894736842, -2.326315789473684, 4.873684210526316, -1.226315789473684, -1.1263157894736842, -2.2263157894736842, 3.473684210526316, -1.426315789473684, 2.7736842105263158, -1.726315789473684, -1.8263157894736841, -0.3263157894736839]
[19.94736842105263, -24.05263157894737, -60.05263157894737, -0.05263157894736992, 28.94736842105263, 105.94736842105263, -120.05263157894737, 19.94736842105263, 108.94736842105263, -84.05263157894737, -24.05263157894737, 74.94736842105263, 35.94736842105263, -105.05263157894737, 15.94736842105263, -76.05263157894737, 93.94736842105263, 7.94736842105263, -19.05263157894737]
113.37684210526314 84204.94736842104
2.44278574911237 66.57206122075577